# Generated by Django 5.1.1 on 2024-10-19 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usercore_max_aquariums'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercore',
            name='max_aquariums',
            field=models.BooleanField(default=True),
        ),
    ]
