# Generated by Django 5.1.1 on 2024-11-22 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_quality_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aquarium',
            name='description',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='freshwaterparameterlogentry',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='name',
            field=models.CharField(max_length=65),
        ),
    ]
