# Generated by Django 5.1.1 on 2024-12-04 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_quality_management', '0002_aquarium_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenanceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='freshwaterparameterlogentry',
            name='ai_suggestions',
            field=models.TextField(blank=True, default='', max_length=750),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='description',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='aquarium',
            name='name',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='freshwaterparameterlogentry',
            name='ammonia',
            field=models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('0.25', '0.25'), ('0.5', '0.5'), ('1.0', '1.0'), ('2.0', '2.0'), ('4.0', '4.0'), ('8.0', '8.0')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='freshwaterparameterlogentry',
            name='high_range_ph',
            field=models.CharField(choices=[('N/A', 'N/A'), ('7.4', '7.4'), ('7.8', '7.8'), ('8.0', '8.0'), ('8.2', '8.2'), ('8.4', '8.4'), ('8.8', '8.8')], default='7.4', max_length=3),
        ),
        migrations.AlterField(
            model_name='freshwaterparameterlogentry',
            name='nitrate',
            field=models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('5.0', '5.0'), ('10', '10'), ('20', '20'), ('40', '40'), ('80', '80'), ('160', '160')], default='0', max_length=3),
        ),
        migrations.AlterField(
            model_name='freshwaterparameterlogentry',
            name='nitrite',
            field=models.CharField(choices=[('N/A', 'N/A'), ('0', '0'), ('0.25', '0.25'), ('0.5', '0.5'), ('1.0', '1.0'), ('2.0', '2.0'), ('5.0', '5.0')], default='0', max_length=4),
        ),
        migrations.AlterField(
            model_name='freshwaterparameterlogentry',
            name='notes',
            field=models.TextField(blank=True, default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='freshwaterparameterlogentry',
            name='ph',
            field=models.CharField(choices=[('N/A', 'N/A'), ('6.0', '6.0'), ('6.4', '6.4'), ('6.6', '6.6'), ('6.8', '6.8'), ('7.0', '7.0'), ('7.2', '7.2'), ('7.6', '7.6')], default='6.0', max_length=3),
        ),
        migrations.CreateModel(
            name='MaintenanceLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('notes', models.TextField(blank=True, default='', max_length=250)),
                ('aquarium', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='water_quality_management.aquarium')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('maintenance_type', models.ManyToManyField(to='water_quality_management.maintenancetype')),
            ],
        ),
    ]
