# Generated by Django 5.1.1 on 2024-12-04 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('water_quality_management', '0003_maintenancetype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='freshwaterparameterlogentry',
            name='openai_token_available',
            field=models.BooleanField(default=True),
        ),
    ]
